language: node_js
node_js:
  - 10.15

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
    tags: true

env:
  EXTENSION_ID=ockddcaogdonfmcfhdblbflchnjgiilc
